languageCode = "en"
languageName = "English"
languageDirection = "ltr"
weight = 1

title = "Alexander Seda"
# copyright = "Copy, _right?_ :thinking_face:"

[params]
  dateFormat = "2 January 2006"

  # mainSections = ["section1", "section2"]
  # description = "My awesome website"

[params.author]
  name = "Alexander Seda"
  image = "img/alex-seda.jpg"
  headline = "Faith • Tech • Music"
  # bio = "A little bit about you"
  links = [
    { resume = "/files/Alexander_Seda_Resume.pdf" },
    { email = "mailto:alexander.seda@outlook.com" },
    { facebook = "https://www.facebook.com/profile.php?id=100089731850680" },
    { github = "https://github.com/Alex-Seda" },
    { instagram = "https://www.instagram.com/alex__seda/" },
    { linkedin = "https://www.linkedin.com/in/alexander-seda-b32184329/" },
  ]
